const hours={0:null,1:null,2:{o:690,c:1260},3:{o:690,c:1260},4:{o:690,c:1260},5:{o:690,c:1260},6:{o:690,c:1260}};
function nowIST(){const d=new Date(),u=d.getTime()+d.getTimezoneOffset()*60000;return new Date(u+19800000)}
function status(){const d=nowIST(),h=hours[d.getDay()],m=d.getHours()*60+d.getMinutes();if(!h)return{open:false,text:"Closed today · Opens Tuesday 11:30 AM"};if(m>=h.o&&m<h.c)return{open:true,text:"Open now · Closes 9:00 PM"};if(m<h.o)return{open:false,text:"Opens today at 11:30 AM"};return{open:false,text:"Closed · Opens tomorrow 11:30 AM"}}
function renderStatus(){const s=status();document.querySelectorAll("[data-status]").forEach(e=>e.textContent=s.text);document.querySelectorAll("[data-status-dot]").forEach(e=>{e.classList.toggle("open",s.open);e.classList.toggle("closed",!s.open)})}
function setupMenu(){const h=document.querySelector(".header"),b=document.querySelector(".menu-toggle");b?.addEventListener("click",()=>h.classList.toggle("open"));document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>h.classList.remove("open")))}
function setupReviews(){const t=document.querySelector("[data-review-track]");if(!t)return;let i=0;const cards=[...t.children];const view=()=>innerWidth<561?1:innerWidth<1051?2:3;function move(n){const max=Math.max(0,cards.length-view());i=n<0?max:n>max?0:n;const w=cards[0].getBoundingClientRect().width;t.style.transform=`translateX(-${i*(w+18)}px)`}document.querySelector("[data-next]")?.addEventListener("click",()=>move(i+1));document.querySelector("[data-prev]")?.addEventListener("click",()=>move(i-1));setInterval(()=>move(i+1),5000);addEventListener("resize",()=>move(i))}
document.addEventListener("DOMContentLoaded",()=>{renderStatus();setInterval(renderStatus,60000);setupMenu();setupReviews();const y=document.querySelector("[data-year]");if(y)y.textContent=new Date().getFullYear()});

function setupHero(){const r=document.querySelector("[data-hero]");if(!r)return;const slides=[...r.querySelectorAll(".hero-slide")],dots=[...r.querySelectorAll(".hero-dots button")];let i=0,t;function show(n){i=(n+slides.length)%slides.length;slides.forEach((s,k)=>s.classList.toggle("active",k===i));dots.forEach((d,k)=>d.classList.toggle("active",k===i))}function restart(){clearInterval(t);t=setInterval(()=>show(i+1),5600)}r.querySelector(".next")?.addEventListener("click",()=>{show(i+1);restart()});r.querySelector(".prev")?.addEventListener("click",()=>{show(i-1);restart()});dots.forEach((d,k)=>d.addEventListener("click",()=>{show(k);restart()}));let sx=0;r.addEventListener("touchstart",e=>sx=e.changedTouches[0].clientX,{passive:true});r.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45){show(i+(dx<0?1:-1));restart()}},{passive:true});restart()}
document.addEventListener("DOMContentLoaded",setupHero);
